name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: pull the docker image from Dockerhub
      run: sudo docker pull vsathiya230/sample:latest
    - name: Delete old docker container
      run: sudo docker rm -f sample-container || true
    - name: Run the Docker container
      run: sudo docker run -d -p 8080:8080 --name sample-container vsathiya230/sample:latest
